---
- block:


  - name: Add VMware hosts
    add_host:
      name: "{{ item }}"
      ansible_user: root
      ansible_ssh_pass: "{{ hostvars[item].root_password }}"
      ansible_pipelining: true
    with_items:
      -  "{{ groups['vmware_esx_hosts'][0] }}"

  - name: Set parameters
    set_fact:
      sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+VjThdZR0QfUCLtU/pIHsrOm5l7YOQ2t5SuWJuia8HWwsL2P2ghunQmQNOwtLVaj5Yge7w1uGMUBIxrwg8vjJ0gqub7eecN+6aCijJaC88+0R17b6r49CKwd3Tspl9ZcZ1Ou8esoBtzwaEvCupuw/UE5pnTnNbiUaV8y7FQChNssIiNnyE6BfRUJJsBw2R2/VdIwfISVdNWjdUFlMjeQuaJLSNTN/FTKs1UVrJCedRX3lZb8OEhtzAaREsh86Y+UmR5/2r1DnLU2pmaua99vETiNi1NJ/OhpWMmG1oFOz5AHXnndt/N7/X4/ogMoMWxBRi+jwJCBR53NXxX9nEUUb root@localhost.localdomain'

  - name: Add new public key to remote authorized_keys file
    delegate_to: "{{ item }}"
    authorized_key:
      key: "{{ sshPublicKey }}"
      user:  "{{ ansible_ssh_user }}"
      state: present
      exclusive: no
      path: /etc/ssh/keys-root/authorized_keys
    with_items:
      -  "{{ groups['vmware_esx_hosts'][0] }}"


  - name: Get RHV provider ID
    uri:
      url: "https://{{ inventory_hostname }}/api/providers/?filter[]=name={{ v2v_ci_rhv_name }}&expand=resources"
      user: "{{ miq_app_username | default('admin') }}"
      password: "{{ miq_app_password | default('smartvm') }}"
      method: GET
      validate_certs: no
    register: rhv_provider_json

  - set_fact:
      query: "resources[?name=='{{ v2v_ci_rhv_name }}'].id"

  - name: Extracting RHV provider id from JSON
    set_fact:
      rhv_provider_id: "{{ rhv_provider_json.json | json_query(query) | first }}"

  - name: Get custom attribute {{ provider_concurrent_max_name }}
    uri:
      url: "https://{{ inventory_hostname }}/api/providers/{{ rhv_provider_id }}/custom_attributes/?filter[]=name={{ provider_concurrent_max_name | regex_replace(' ', '%20') }}"
      user: "{{ miq_app_username }}"
      password: "{{ miq_app_password }}"
      method: GET
      validate_certs: no
    register: max_transorm_runners_json

  - name: Add custom attribute {{ provider_concurrent_max_name }}
    uri:
      url: "https://{{ inventory_hostname }}/api/providers/{{ rhv_provider_id }}/custom_attributes/"
      user: "{{ miq_app_username | default('admin') }}"
      password: "{{ miq_app_password | default('smartvm') }}"
      method: POST
      validate_certs: no
      body_format: json
      body:
        action: add
        resource:
          name: "{{ provider_concurrent_max_name }}"
          value: "{{ provider_concurrent_max }}"

  tags:
    - miq_set_provider_concurrent_vm_migration_max

