#!/usr/bin/env bash

set -xe

VENV=.ansbile

if [[ ! -d "$VENV" ]]
then
    virtualenv --system-site-packages ${VENV}
    source ${VENV}/bin/activate
    pip install -U -r requirements.txt -q
    deactivate
fi

source ${VENV}/bin/activate

ansible-playbook --version

INVENTORY=$1
shift
PLAYBOOK=$1
shift

SSH_KEY=""
if [[ -e "$HOME/jenkins_ssh_key" ]]
then
    SSH_KEY="--key-file $HOME/jenkins_ssh_key"
fi
if [[ -n "$JENKINS_URL" ]]
then
    # Running on Jenkins we want to see colorful output
    export ANSIBLE_FORCE_COLOR=true
fi

REQ_DIR=${WORKSPACE}/roles-deps
ROLE_DEPS=${WORKSPACE}/roles-deps.yml

if [[ -e "$ROLE_DEPS" ]]
then
    rm -rf "$REQ_DIR"
    mkdir -p "$REQ_DIR"
    ansible-galaxy install -f -r "$ROLE_DEPS" -p "$REQ_DIR"
    export ANSIBLE_ROLES_PATH="$REQ_DIR"
fi

export PYCURL_SSL_LIBRARY=nss

if [[ -e "$WORKSPACE/requirements.txt" ]]
then
    pip install -U -r ${WORKSPACE}/requirements.txt -q
fi

export ANSIBLE_SSH_RETRIES=10
export ANSIBLE_HOST_KEY_CHECKING=False

pushd ${WORKSPACE}

[[ -e "$PLAYBOOK" ]]

ansible-playbook \
    -u root \
    -i "$INVENTORY" \
    ${SSH_KEY} "$@" ${PLAYBOOK}

popd
deactivate
